resources:
  secret_scopes:
    {{name}}:
      name: "${bundle.target}-{{name}}-kv-secret-scope"
      backend_type: AZURE_KEYVAULT
      keyvault_metadata:
        resource_id: ${var.keyvault_resource_id}
        dns_name: ${var.keyvault_dns_name}
      {% if permissions is defined %}
      permissions:
      {% for group in permissions.groups %}
        - group_name: "{{ group.group_name }}"
          level: "{{ group.level }}"
      {% endfor %}

      {% for user in permissions.users %}
        - user_name: "{{ user.user_name }}"
          level: "{{ user.level }}"
      {% endfor %}

      {% for service_principal in permissions.service_principals %}
        - service_principal_name: "{{ service_principal.service_principal_name }}"
          level: "{{ service_principal.level }}"
      {% endfor %}
      {% endif %}
