# SQL Warehouse for Transformation
#
# Purpose:
#   - Used for SQL data transformation workloads
#

variables:
  transformation_warehouse_type:
    default: {{warehouse_type}}
  transformation_enable_serverless_compute:
    default: {{enable_serverless_compute}}

# Environment-Specific Compute:
#   - In DEV: Use classic clusters (lower cost, familiar behavior)
#   - In UAT/PROD: Use serverless (better performance & scaling)
#   - Controlled via variables: var.transform_warehouse_type & var.enable_serverless_bool

resources:
  sql_warehouses:
    {{name}}:

      # ------------------------------
      # Warehouse Identity
      # ------------------------------
      name: {{name}}_wh

      # ------------------------------
      # Environment-Specific Compute
      # ------------------------------
      warehouse_type: "${var.transformation_warehouse_type}"      # e.g., "CLASSIC" OR "PRO"
      enable_serverless_compute: "${var.transformation_enable_serverless_compute}" # Toggle based on environment

      # ------------------------------
      # Compute & Scaling
      # ------------------------------

      # Cluster size options:
      # 2X-Small, X-Small, Small, Medium, Large, X-Large, 2X-Large, 3X-Large, 4X-Large

      cluster_size: {{cluster_size}}
      min_num_clusters: {{min_num_clusters}}
      max_num_clusters: {{max_num_clusters}}
      auto_stop_mins: {{auto_stop_mins}}

      # Spot Instance Policy
      # - COST_OPTIMIZED        : Favors spot-priced instances (lower cost, variable availability)
      # - RELIABILITY_OPTIMIZED : Favors on-demand instances (higher availability)
      spot_instance_policy: "COST_OPTIMIZED"

      # ------------------------------
      # Metadata / Tags
      # ------------------------------
      tags:
        custom_tags:
          - key: "Environment"
            value: "${bundle.target}"
          - key: "Bundle"
            value: "${bundle.name}"
          - key: "Provisioned By"
            value: "DABS"

      # ------------------------------
      # Permissions (Access Control)
      # ------------------------------
      # permissions:
      #   - group_name: ""  # Databricks group name
      #     level: ""       # CAN_USE | CAN_VIEW | CAN_MONITOR | CAN_MANAGE

      #   - user_name: ""   # Databricks user email (e.g. user@company.com)
      #     level: ""       # CAN_USE | CAN_VIEW | CAN_MONITOR | CAN_MANAGE
      {% if permissions is defined %}
      permissions:
      {% for group in permissions.groups %}
        - group_name: "{{ group.group_name }}"
          level: "{{ group.level }}"
      {% endfor %}

      {% for user in permissions.users %}
        - user_name: "{{ user.user_name }}"
          level: "{{ user.level }}"
      {% endfor %}

      {% for service_principal in permissions.service_principals %}
        - service_principal_name: "{{ service_principal.service_principal_name }}"
          level: "{{ service_principal.level }}"
      {% endfor %}
      {% endif %}
